DEVICE_PATH := device/oppo/OP4E49

# AAPT configuration
APT_CONFIG := normal
APT_SCREEN_DENSITY := 480

# Audio
USE_XML_AUDIO_POLICY_CONF := 1

# Bluetooth
BOARD_HAVE_BLUETOOTH := true

# Graphics
TARGET_USES_HWC2 := true
TARGET_USES_GRALLOC1 := true

# OrangeFox Recovery
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
OF_FORCE_PREBUILT_KERNEL := 1
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := 1
FOX_AB_DEVICE := 0
TARGET_ARCH := arm64

# TWRP configuration
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := false
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_RESETPROP := 1
TW_INCLUDE_REPACKTOOLS := true
TW_HAS_MTP := true
TW_MTP_DEVICE := /dev/mtp_usb
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 2048
TW_DEFAULT_BRIGHTNESS := 1200
TW_EXCLUDE_NANO := true
TW_EXCLUDE_APEX := true
TW_INCLUDE_FASTBOOTD := true
TW_NO_EXFAT_FUSE := 1
TW_INCLUDE_NTFS_3G := true
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
TARGET_USES_MKE2FS := 1
TW_EXCLUDE_TWRPAPP := true
TW_INCLUDE_LPTOOLS := 1
TW_OZIP_DECRYPT_KEY := 0
OF_FLASHLIGHT_ENABLE := 1

# TWRP Recovery
RECOVERY_SDCARD_ON_DATA := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := /config/usb_gadget/g1/functions/mass_storage.0/lun.%d/file
TARGET_RECOVERY_LCD_BACKLIGHT_PATH := "/sys/class/leds/lcd-backlight/brightness"

# Encryption
PLATFORM_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0
PLATFORM_SDK_VERSION := 30
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE_METADATA_DECRYPT := 1

# Screen
OF_SCREEN_H := 2400
OF_STATUS_H := 144
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_ALLOW_DISABLE_NAVBAR := 0

# USB
BOARD_USES_USB_MASS_STORAGE := 1
BOARD_USB_CONTROLLER := 11200000.usb_xhci
